config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, controllers: { registrations: 'registrations' }, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up', to: 'registrations#new', as: :new_user_registration
    post 'users', to: 'registrations#create', as: :user_registration
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :users, only: [:new, :create, :index]
    resources :faculties, only: [:new, :create, :destroy, :index]
  end

  resources :workspace, only: [:new, :create]
  post 'delete_folder', to: 'workspace#delete_folder'

  resources :documents do
    member do
      get :download
      patch :update
    end
    collection do
      get :index
      get :search
    end
  end

  resources :faculties, only: [:show]

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  
  root "knowledge_app#index"
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :folders, dependent: :destroy

  validates :name, presence: true

  after_create :create_faculty_folder

  private

  def create_faculty_folder
    root_folder = Folder.root_folder
    Folder.create!(name: name, parent_folder: root_folder, faculty: self)
  end
end

app/controllers/admin/faculties_controller.rb
module Admin
  class FacultiesController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin

    def index
      @faculties = Faculty.all
    end

    def new
      @faculty = Faculty.new
    end

    def create
      @faculty = Faculty.new(faculty_params)

      if Faculty.exists?(name: @faculty.name)
        flash[:alert] = "A faculty with this name already exists."
        render :new and return
      end

      Rails.logger.info("Creating faculty with params: #{faculty_params.inspect}")
      if @faculty.save
        redirect_to admin_faculties_path, notice: 'Faculty created successfully.'
      else
        Rails.logger.error("Failed to create faculty: #{@faculty.errors.full_messages.to_sentence}")
        render :new
      end
    end

    def destroy
      @faculty = Faculty.find_by(id: params[:id])

      if @faculty.nil?
        redirect_to admin_faculties_path, alert: "Faculty not found."
      elsif delete_faculty_and_associations(@faculty)
        redirect_to root_path, notice: 'Faculty and all associated data were successfully deleted.'
      else
        redirect_to admin_faculties_path, alert: 'Failed to delete faculty. Please try again.'
      end
    end

    private

    def authorize_admin
      redirect_to root_path, alert: 'You are not authorized to access this page.' unless current_user.admin?
    end

    def faculty_params
      params.require(:faculty).permit(:name)
    end

    def delete_faculty_and_associations(faculty)
      ActiveRecord::Base.transaction do
        faculty.folders.includes(:documents).each do |folder|
          folder.documents.destroy_all
        end
        faculty.folders.each do |folder|
          delete_subfolders_and_folders(folder)
        end
        faculty.destroy!
      end
    rescue StandardError => e
      Rails.logger.error("Failed to delete faculty and associated records: #{e.message}")
      false
    end
    

    def delete_subfolders_and_folders(folder)
      folder.documents.destroy_all
      folder.subfolders.each do |subfolder|
        delete_subfolders_and_folders(subfolder)
      end
      folder.destroy!
    end
    
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :authenticate_user!

  def show
    @faculty = Faculty.find(params[:id])
    @members = @faculty.users
    @documents = Document.where(faculty_id: @faculty.id)
  end
end

app/views/faculties/show.html.erb
<h1 class="faculty-title"><%= @faculty.name %></h1>

<% if current_user.admin? %>
  <div class="button-container">
    <%= button_to 'Delete Faculty', admin_faculty_path(@faculty), method: :delete, data: { confirm: 'Are you sure you want to delete this faculty?' }, class: 'btn btn-danger delete-button' %>
  </div>
<% end %>

<h2 class="section-title">Faculty Members</h2>
<% if @members.any? %>
  <table class="user-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= link_to member.name, user_path(member) %></td>
          <td><%= member.email %></td>
          <td><%= member.role.humanize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-center">No faculty members found.</p>
<% end %>

<h2 class="section-title">Documents</h2>
<% if @documents.any? %>
  <table class="user-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Path</th>
        <th>Created By</th>
        <th>Last Updated</th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= link_to document.title, document_path(document) %></td>
          <td>
            <% path = []
            current_folder = document.folder
            while current_folder
              path.unshift(current_folder.name)
              current_folder = current_folder.parent_folder
            end
            path.push(document.title + '.md') %>
            <%= path.join('/') %>
          </td>
          <td><%= document.user.name %></td>
          <td><%= document.updated_at.strftime("%B %d, %Y %H:%M:%S") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-center">No documents found for this faculty.</p>
<% end %>