config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users, controllers: { registrations: 'registrations' }, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up', to: 'registrations#new', as: :new_user_registration
    post 'users', to: 'registrations#create', as: :user_registration
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :users, only: [:new, :create, :index]
    resources :faculties, only: [:new, :create, :destroy, :index]
  end

  resources :workspace, only: [:new, :create]
  post 'delete_folder', to: 'workspace#delete_folder'

  resources :documents do
    member do
      get :download
      patch :update
    end
    collection do
      get :index
      get :search
    end
  end

  resources :faculties, only: [:show]

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  
  root "knowledge_app#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KnowledgeApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <%= javascript_importmap_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="nav-left">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
    </div>
    <div class="nav-right">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to 'Users', admin_users_path, class: 'nav-link'%>
          <%= link_to 'Faculties', admin_faculties_path, class: 'nav-link'%>
        <% end %>
        <% if current_user.admin? ||current_user.faculty_member? %>
          <%= link_to 'Workspace', new_workspace_path, class: 'nav-link' %>
        <% end %>
        <%= link_to 'Documents', documents_path, class: 'nav-link' %>
        <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      <% end %>
    </div>
  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>